// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE2YGIXOomHYLavufspR9isnzMTzIqX3U',
    appId: '1:680422958201:web:078b0c23c76e195f9ee0a8',
    messagingSenderId: '680422958201',
    projectId: 'spotify-clone-9da78',
    authDomain: 'spotify-clone-9da78.firebaseapp.com',
    storageBucket: 'spotify-clone-9da78.appspot.com',
    measurementId: 'G-MJRYRSWX4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Mha0Rs9yMf81jAoRWqGJQnOv0ZgVbeE',
    appId: '1:680422958201:android:6d28a39fa7002eb39ee0a8',
    messagingSenderId: '680422958201',
    projectId: 'spotify-clone-9da78',
    storageBucket: 'spotify-clone-9da78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXMcaG7tKiKcxNd6PoJa41gdWpsxdHmwg',
    appId: '1:680422958201:ios:c5b96b1dc9a7e0439ee0a8',
    messagingSenderId: '680422958201',
    projectId: 'spotify-clone-9da78',
    storageBucket: 'spotify-clone-9da78.appspot.com',
    iosBundleId: 'com.example.flutterSpotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXMcaG7tKiKcxNd6PoJa41gdWpsxdHmwg',
    appId: '1:680422958201:ios:c5b96b1dc9a7e0439ee0a8',
    messagingSenderId: '680422958201',
    projectId: 'spotify-clone-9da78',
    storageBucket: 'spotify-clone-9da78.appspot.com',
    iosBundleId: 'com.example.flutterSpotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE2YGIXOomHYLavufspR9isnzMTzIqX3U',
    appId: '1:680422958201:web:7a4614ae98e8ba159ee0a8',
    messagingSenderId: '680422958201',
    projectId: 'spotify-clone-9da78',
    authDomain: 'spotify-clone-9da78.firebaseapp.com',
    storageBucket: 'spotify-clone-9da78.appspot.com',
    measurementId: 'G-JWF7LHDPEE',
  );

}